// Writes dist/_headers for Cloudflare Pages after `astro build`.
//
// The Content-Security-Policy allows scripts by hash: every inline <script> in the built HTML
// is hashed here, so the policy stays exact without 'unsafe-inline' for scripts. Styles need
// 'unsafe-inline' because the stylesheet is inlined and Shiki colours code with style attributes.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
// Cloudflare Web Analytics loads its beacon from one origin and reports to another.
const ANALYTICS_SCRIPT = 'https://static.cloudflareinsights.com';
const ANALYTICS_CONNECT = 'https://cloudflareinsights.com';

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const path = join(dir, e.name);
    if (e.isDirectory()) return htmlFiles(path);
    return e.name.endsWith('.html') ? [path] : [];
  });
}

const hashes = new Set();
for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8');
  for (const m of html.matchAll(/<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g)) {
    const attrs = m[1] ?? '';
    // JSON-LD is data, not executed script, so CSP does not apply to it.
    if (/type="application\/ld\+json"/.test(attrs)) continue;
    hashes.add(`'sha256-${createHash('sha256').update(m[2] ?? '').digest('base64')}'`);
  }
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(' ')} ${ANALYTICS_SCRIPT}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src 'self' ${ANALYTICS_CONNECT}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

// Cloudflare merges headers from every matching rule, so rules for assets first detach the
// default Cache-Control with "! Cache-Control" before setting their own.
const headers = `# Generated by scripts/postbuild.mjs. Edit that script, not this file.

/*
  Cache-Control: no-cache
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  X-Frame-Options: DENY

/_astro/*
  ! Cache-Control
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  ! Cache-Control
  Cache-Control: public, max-age=2592000

/og/*
  ! Cache-Control
  Cache-Control: public, max-age=86400
`;

writeFileSync(join(DIST, '_headers'), headers);
console.log(
  `postbuild: wrote ${relative('.', join(DIST, '_headers'))} with ${hashes.size} script hashes`,
);

// GitHub Pages serves plain static files with no way to set response headers, so the _headers
// file above only takes effect if the site is ever fronted by Cloudflare again. As a fallback,
// inject the header-equivalent <meta> tags directly into each page. This is a strictly weaker
// substitute: meta CSP silently ignores frame-ancestors, so clickjacking protection (that
// directive and X-Frame-Options, which has no meta form at all) is not replicated by this and
// is simply absent when the site is served as plain static files.
const metaCsp = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(' ')} ${ANALYTICS_SCRIPT}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src 'self' ${ANALYTICS_CONNECT}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  'upgrade-insecure-requests',
].join('; ');

for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8');
  const withMeta = html.replace(
    '<meta charset="utf-8">',
    `<meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="${metaCsp}"><meta name="referrer" content="strict-origin-when-cross-origin">`,
  );
  if (withMeta !== html) writeFileSync(file, withMeta);
}
console.log('postbuild: inlined CSP and referrer <meta> tags for static hosting without headers');
